### PR TITLE
Minor: a couple of doc fixes in the XForms doc section

### PR DESCRIPTION
**Pull request by Gubaer**

### CODE REVIEW

**Comment by ebruchez** [comment]
Lots of good catches again, thanks!

**Comment by ebruchez** [comment]
By the way @Gubaer I don't think we got a CLA from you. Would you agree to sign and send it to us? You can find it here:

```
http://wiki.orbeon.com/forms/community/cla
```

I realize that we are asking this a posteriori. We have been more diligent asking this for code contributions but didn't think about the doc. The benefit is that it makes things much clearer. It follows the [Apache CLA](https://www.apache.org/licenses/icla.txt) so is very standard. Thanks!

**Comment by Gubaer** [comment]
You can download the signed CLA here: https://tresor.it/s#cXFZ9cWWqFGiO1796XI4oA 
(link works next five days, for max. 10 attempts)

**Comment by ebruchez** [comment]
Excellent, thanks, it's now downloaded.

**Pull request merged**
